name: DataCollector Nuget package build

on:
  push:
      branches:
        - develop

jobs:
  build_NuGet:
    runs-on: ubuntu-latest
    environment: Nuget
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Intall nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGETKEY }}
      - name: Set env
        run: echo "RELEASE_VERSION=${{ needs.version.outputs.version-tag }}" >> $GITHUB_ENV


      # - name: Update nugets and dependecies
      #   run: dotnet restore src/HSMSensorDataObjects/HSMSensorDataObjects.csproj --force

      # - name: Build Sensor objects
      #   run: dotnet build src/HSMSensorDataObjects/HSMSensorDataObjects.csproj -c Release

      # - name: Pack package
      #   run: dotnet pack src/HSMSensorDataObjects/HSMSensorDataObjects.csproj -p:PackageID=HSMDataCollector.HSMSensorDataObjects -c Release --no-build

      # - name: Push nuget package
      #   run: dotnet nuget push src/HSMSensorDataObjects/bin/Release/HSMDataCollector.HSMSensorDataObjects*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json

      - name: Update nugets and dependecies
        run: dotnet restore src/HSMDataCollector/HSMDataCollector.sln --force

      - name: Build Sensor objects
        run: dotnet build src/HSMDataCollector/HSMDataCollector/HSMDataCollector.csproj -c Release --no-restore

      - name: Pack package
        run: dotnet pack src/HSMDataCollector/HSMDataCollector/HSMDataCollector.csproj -p:PackageID=HSMDataCollector.HSMDataCollector -c Release --no-build

      - name: Push nuget package
        run: dotnet nuget push src/HSMDataCollector/HSMDataCollector/bin/Release/HSMDataCollector.HSMDataCollector*.nupkg --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json